spring:
  application:
    name: product-service
  threads:
    virtual:
      enable: true
      data:
        mongodb:
          uri: mongodb://root:password@localhost:27017/product-db?authSource=admin

  server:
    port: 8080
